package com.guan.domain;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.guan.dto.CommentDto;

import lombok.Data;


@Data @Document
public class Comment {
    @Id
    private ObjectId id; //id is generated by DB
    private float rate = 0f;
    private String comment;
    private String username; //inserted when creating
    private String reply; 
    @Indexed
    private String postId; //inserted when creating
    
    public Comment() {}
    //used when saving a new comment
    public Comment(CommentDto dto) {
        this.rate = dto.getRate();
        this.comment = dto.getComment();
        this.postId = dto.getPostId();
    }
    
}